config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts
  resources :relationships, only: [:create, :destroy]
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
    validates :user_id, presence: true
    validates :content, presence: true, length: { maximum: 140 }
    validates :storename, presence: true
    validates :productname, presence: true
    validates :rating, presence: true
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
end

app/models/store.rb
class Store < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  validates :screen_name, presence: true, length: { maximum: 50 }, on: :update
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :region, presence: true, length: { maximum: 20 }, on: :update
  validates :phone_number, presence: true, format: { with: /\A\+?\d[-\d\s]+\Z/, message: "Use only digits and dashes for phone number" }, length: {maximum: 20}, on: :update
  has_secure_password
  has_many :microposts
  has_many :stores
  
  has_many :following_relationships, class_name:  "Relationship",
                                     foreign_key: "follower_id",
                                     dependent:   :destroy
  has_many :following_users, through: :following_relationships, source: :followed
  
  has_many :follower_relationships, class_name:  "Relationship",
                                    foreign_key: "followed_id",
                                    dependent:   :destroy
  has_many :follower_users, through: :follower_relationships, source: :follower
  
  # 他のユーザーをフォローする
  def follow(other_user)
    following_relationships.find_or_create_by(followed_id: other_user.id)
  end

  # フォローしているユーザーをアンフォローする
  def unfollow(other_user)
    following_relationship = following_relationships.find_by(followed_id: other_user.id)
    following_relationship.destroy if following_relationship
  end

  # あるユーザーをフォローしているかどうか？
  def following?(other_user)
    following_users.include?(other_user)
  end
  
  def feed_items
    Micropost.where(user_id: following_user_ids + [self.id])
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
  before_action :set_locale
 
  def set_locale
      I18n.locale = params[:locale]|| I18n.default_locale
  end

  def default_url_options(options={})
      { locale: I18n.locale }
  end

  private
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = t(:log_in_please) #"Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create]

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = t(:micropost_created) 
      redirect_to root_url
    else
      @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc) # この行を追加
      render 'static_pages/home'
    end
  end
  
  def destroy
    @micropost = current_user.microposts.find_by(id: params[:id])
    return redirect_to root_url if @micropost.nil?
    @micropost.destroy
    flash[:success] = t(:micropost_deleted)
    redirect_to request.referrer || root_url
  end
  
  private
  def micropost_params
    params.require(:micropost).permit(:content, :storename, :address, :city, :state, :zip, :website, :productname, :productprice, :rating)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :logged_in_user

  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
  end

  def destroy
    @user = current_user.following_relationships.find(params[:id]).followed
    current_user.unfollow(@user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:info] = t('logged_in_as', user: @user.name) 
      redirect_to @user
    else
      flash[:danger] = t(:login_error) 
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc)
    end
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @store = Store.new
  end

  def create
    @store = Store.new(store_params)
    if @store.save
      redirect_to root_path
      flash[:notice] = '店舗追加が出来ました'
    else
       @store = Store.all
       flash.now[:alert] = "メッセージの保存に失敗しました。"
       render 'index'
    end
  end

private
  def store_params
    params.require(:store).permit(:restaurantName, :restaurantAdd, :restaurantPhone, :restaurantWebsite, :productName, :productPrice, :productRating, :comments)
  end
end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :authorized_access!, only: [:edit, :update]

  def show # 追加
   @user = User.find(params[:id])
   @microposts = @user.microposts.order(created_at: :desc)
   @users = @user.following_users
  end

  def index
    @users = User.all
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
       # unvalidated
      render 'edit'
    end
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Cappuciniaにようこそ！"
      redirect_to @user
    else
      render 'new'
    end
  end

  private
  
  def set_user
    @user = User.find(params[:id])
  end  
  
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :region, :phone_number, :screen_name)
  end
  
  def authorized_access!
    if @user != current_user
      redirect_to root_path, alert: '未承認アクセスエラー!'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Cappucinia", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <% if I18n.locale == I18n.default_locale %>
              <%= link_to "English", { :locale=>'en' } %>
          <% else %>
              <%= link_to "日本語", { :locale=>'ja' } %>
          <%end%>
        </li>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", '#' %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cappucinia</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
 <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %> <!-- ここから -->
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %> <!-- ここまで追加 -->
    <%= yield %>
  </div>
</body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content"><%= micropost.storename %></span>
  <span class="content"><%= micropost.address %></span>
  <span class="content"><%= micropost.city %> <%= micropost.state %> <%= micropost.zip %></span>
  <span class="content"><%= micropost.productname %> - <%= micropost.productprice %> <%= t(:store_rating) %> <%= micropost.rating %></span>
  <span class="content"><p>Comments:</p><%= micropost.content %></span>
  <span class="timestamp">
    <%= t('posted_time_ago', posted_ago: time_ago_in_words(micropost.created_at)) %>
    <% if current_user == micropost.user %>
      <%= link_to t(:delete_post), micropost, method: :delete,
                                       data: { confirm: t(:confirm_delete) } %> 
    <% end %>
  </span>
</li>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= t(:store_name) %>
  <div class="field">
    <%= f.text_field :storename %>
  </div>
  
  <%= t(:store_address) %>
  <div class="field">
    <%= f.text_field :address %>
  </div>
  
  <%= t(:store_city) %>
  <div class="field">
    <%= f.text_field :city %>
  </div>
  
  <%= t(:store_state) %>
  <div class="field">
    <%= f.text_field :state %>
  </div>

  <%= t(:store_zip) %>
  <div class="field">
    <%= f.text_field :zip %>
  </div>
  
  <%= t(:store_website) %>
  <div class="field">
    <%= f.text_field :website %>
  </div>
  
  <%= t(:store_productname) %>
  <div class="field">
    <%= f.text_field :productname %>
  </div>

  <%= t(:store_productprice) %>
  <div class="field">
    <%= f.text_field :productprice %>
  </div>

  <%= t(:store_rating) %>
  <div class="field">
    <%= f.text_field :rating %>
  </div>


  <div class="field">
    <%= f.text_area :content, placeholder: t(:compose_new_post) %>
  </div>  
  <!--- :content is the actual form - there's only one field --->
  <%= f.submit t(:post), class: "btn btn-primary" %>
  <% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to t(:view_my_profile), current_user %></span>
<span><%= @current_user.microposts.count %> <%= t(:cappucinia_created, count: current_user.microposts.count) %></span>
<!---<span><%= t(:cappucinia_created, count: @current_user.microposts.count) %></span> 
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>--->

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3><%= t(:feed_title) %></h3>
      
      <%= render 'shared/feed' %>
    </div>
   </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to Cappucinia!</h1>
      Get ready to enjoy coffee on a whole new level!
      <p>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
    </p>
  </div>
<% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/edit.html.1.erb
<%= form_for(@user, html: {class: "form-horizontal"}) do |f| %>
  <% if @user.errors.present? %>
    <div class="alert alert-danger">
      <%= alert %>
      <ul>
        <% @user.errors.full_messages.each do |full_message| %>
          <li>
            <%= full_message %>
          </li>
        <% end %> 
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, size: 40, maxlength: 20, readonly: true, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, size: 40, maxlength: 255, class: "form-control" %>
    </div>
  </div>
    <div class="form-group">
    <%= f.label :screen_name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :screen_name, size: 40, maxlength: 255, class: "form-control" %>
    </div>
  </div>
    <div class="form-group">
    <%= f.label :region, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :region, size: 40, maxlength: 255, class: "form-control" %>
    </div>
  </div>
    <div class="form-group">
    <%= f.label :phone_number, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :phone_number, size: 40, maxlength: 255, class: "form-control", :placeholder => "数字とハイフンのみ, 03-1234-5678など"%>
    </div>
  </div>
  <!— And others —>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "更新", class: "btn btn-sm btn-primary" %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= form_for(@user, html: {class: "form-horizontal"}) do |f| %>
  <% if @user.errors.present? %>
    <div class="alert alert-danger">
      <%= alert %>
      <ul>
        <% @user.errors.full_messages.each do |full_message| %>
          <li>
            <%= full_message %>
          </li>
        <% end %> 
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label t(:user_form_name), class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, size: 40, maxlength: 20, readonly: true, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label t(:user_form_pass), class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.password_field :password, size: 40, maxlength: 255, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label t(:user_form_passconf), class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.password_field :password_confirmation, size: 40, maxlength: 255, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, size: 40, maxlength: 255, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :screen_name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :screen_name, size: 40, maxlength: 255, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :region, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :region, size: 40, maxlength: 255, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :phone_number, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :phone_number, size: 40, maxlength: 255, class: "form-control", :placeholder => "数字とハイフンのみ, 03-1234-5678など"%>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "更新", class: "btn btn-sm btn-primary" %>
    </div>
  </div>
<% end %>

app/views/users/followers.html.erb
<h1>Followers</h1>
<ul style="list-style: none;">
  <% @user.follower_users.each do |u| %>
    <li class="clearfix" style="margin-bottom: 6px;"><%= gravatar_for u, size: 50 %><%= link_to u.name, u %></li>
  <% end %>
</ul>

app/views/users/followings.html.erb
<h1>Following</h1>
<ul style="list-style: none;">
  <% @user.following_users.each do |u| %>
    <li class="clearfix" style="margin-bottom: 6px;"><%= gravatar_for u, size: 50 %><%= link_to u.name, u %></li>
  <% end %>
</ul>

app/views/users/index.html.erb
<h1><%= t(:registered_users) %></h1>
<ul>
  <% @users.each do |u| %>
    <li><%= link_to u.name, u %>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %> <!-- ここを追加 -->

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-5">
    <section class="user_info">
      <h1 class="clearfix">
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
      <hr class="clearfix">
      <div class="">
        <div class="row">
          <div class="row">
            <div class="col-sm-4 user-label">
            Screen Name
            </div>
          <div class="col-sm-8">
            <%= @user.screen_name %>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-4 user-label">
            Email
          </div>
          <div class="col-sm-8">
            <%= @user.email %>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-4 user-label">
            Region
          </div>
          <div class="col-sm-8">
            <%= @user.region %>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-4 user-label">
            Phone
          </div>
          <div class="col-sm-8">
            <%= @user.phone_number %>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-12"><%= link_to "Followings (#{@user.following_users.count})", followings_user_path(@user) %></div>
        </div>
        <div class="row">
          <div class="col-sm-12"><%= link_to "Followers (#{@user.follower_users.count})", followers_user_path(@user) %></div>
        </div>
      </div>
    </section>
  </aside>
  <div class="col-md-7">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
    <% end %>
  </div>
</div>